name: "PyPI"

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: "build-n-publish"
    runs-on: ubuntu-latest

    steps:
      - name: "checkout repository"
        uses: actions/checkout@v5

      - name: "setup python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: "install python packages"
        run: "python -m pip install --user wheel setuptools"

      - name: "build distribution"
        run: "python setup.py sdist bdist_wheel"

      - name: "publish to pypi"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
